// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVWjaADd-I0XfX8Nj0ApkJltOMZbGsnmo',
    appId: '1:840387515882:web:a995a05bc4e14f1dc28e93',
    messagingSenderId: '840387515882',
    projectId: 'ocard-fp',
    authDomain: 'ocard-fp.firebaseapp.com',
    storageBucket: 'ocard-fp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_aKHeR99tErYY2xf7yGvlQRZqC8xPUCw',
    appId: '1:840387515882:android:6e3629749d64ee55c28e93',
    messagingSenderId: '840387515882',
    projectId: 'ocard-fp',
    storageBucket: 'ocard-fp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvDeEAWFPSrj2bzA7PPXKtBN_E5tWe6Zk',
    appId: '1:840387515882:ios:6c8dcb3e906cdcd9c28e93',
    messagingSenderId: '840387515882',
    projectId: 'ocard-fp',
    storageBucket: 'ocard-fp.appspot.com',
    iosBundleId: 'com.example.oCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvDeEAWFPSrj2bzA7PPXKtBN_E5tWe6Zk',
    appId: '1:840387515882:ios:6c8dcb3e906cdcd9c28e93',
    messagingSenderId: '840387515882',
    projectId: 'ocard-fp',
    storageBucket: 'ocard-fp.appspot.com',
    iosBundleId: 'com.example.oCard',
  );
}
